module.exports = Object.freeze({
  SIGNUP_SUCESSFULL: "Signed up successfully",
  UPDATE_SUCCESS: "Updated successfully",
  NO_RECORD: "No Record found",
  RECORD_SUCCESS: "Record found successfully",
  LOGIN_SUCCESSFULL: "Login successfully",
  LOGOUT: "Logout successfully",
  INVALID_TOKEN: "Invalid token",
  NO_TOKEN: "No token, authorization failed",
  USER_EXISTS: "An account related to this phone number already exists, please try another one",
  PASSWORD_MISMATCH: "The provided passwords do not match",
  SOMETHING_WRONG: "Something went wrong",
  PERMISSION_DENIED: "Permission denied",
  LOGIN_FAILED: "Login failed! Incorrect phone number or password",
  FIRST_NAME: "First name must be between 3 and 30 characters in length",
  LAST_NAME: "Last name must be between 3 and 30 characters in length",
  PASSWORD_LENGTH: "Password must be 6 to 30 characters long",
  PASSWORD_PATTERN: "Password must contain at least one digit, one uppercase letter, one lowercase letter and one special character",
  GENDER_ERROR: "Gender must be either 'male', 'female' or 'other'",
  PHONE_NUMBER: "Phone number must be a number and 10 digits in length",
  NO_USER: "No user found for these credentials",
  NO_AUTH_HEADER: "Authorization header doesn't exist",
  UNAUTHORIZED_ACTION: "You are not authorized to perform this action",
  INVALID_EMAIL: "The email entered is not in correct format",
});
