module.exports = Object.freeze({
  STATUS_IGNORED: "ignored",
  STATUS_INTERESTED: "interested",
  STATUS_ACCEPTED: "accepted",
  STATUS_REJECTED: "rejected",
  INVALID_SEND_STATUS: "The status for sending a connection can be 'ignored' or 'interested'",
  INVALID_REVIEW_STATUS: "The status for reviewing a connection can be 'accepted' or 'rejected'",
  SELF_REQUEST_INVALID: "Cannot send a connection request to self",
  NO_USER_FOR_ID: "No user found for the provided id",
  NO_REQUEST_FOR_ID: "No connection request found for the provided id",
  LIKED_SUCESSFULLY: "Profile liked successfully",
  IGNORED_SUCESSFULLY: "Profile ignored successfully",
  ACCEPTED_SUCESSFULLY: "Connection request accepted successfully",
  REJECTED_SUCESSFULLY: "Connection request rejected successfully",
  REQUEST_ALREADY_EXISTS: "Connection request already exists",
  REVIEW_ONLY_INTERESTED: "Only 'interested' status reqeusts can be reviewed",
  INVALID_REQUEST_ID: "Request id must be a valid id",
});
